/// <reference types="vitest/config" />
import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import path from "node:path";

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: "autoUpdate",
      // Custom worker (src/sw.js) instead of the generated one: navigations must
      // be network-first so a new deploy's HTML shell shows on the FIRST paint.
      // The generated worker served the precached index.html cache-first, which
      // made each deploy briefly paint the previous build's shell.
      strategies: "injectManifest",
      srcDir: "src",
      filename: "sw.js",
      // Icons are pre-generated by scripts/gen-app-icon.mjs into public/. Two families:
      // the "any" icons are the FULL logo (drives the native TWA splash → matches the
      // in-app splash), and "maskable" is the MARK padded (adaptive launcher, un-trimmed).
      manifest: {
        id: "/",
        name: "Food Metrics — Recipe Costing",
        short_name: "Food Metrics",
        description: "Recipe costing, yield and wastage for multi-brand kitchens.",
        theme_color: "#04090b",
        background_color: "#04090b",
        display: "standalone",
        orientation: "any",
        // `?app=1` marks installed-app launches so "/" skips the marketing landing
        // and shows the splash → login/dashboard (see RootEntry in router.tsx).
        start_url: "/?app=1",
        scope: "/",
        categories: ["business", "productivity", "food"],
        icons: [
          { src: "pwa-64x64.png", sizes: "64x64", type: "image/png" },
          { src: "pwa-192x192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "pwa-512x512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          { src: "maskable-icon-512x512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      },
      injectManifest: {
        globPatterns: ["**/*.{js,css,html,svg,png,ico,woff2}"],
        maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
      },
      // navigateFallback / navigateFallbackDenylist / cleanupOutdatedCaches now
      // live in src/sw.js — the SPA offline fallback is the precached
      // index.html, served only when the network fetch fails.
      devOptions: { enabled: false },
    }),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  // Bind to 0.0.0.0 so the app is reachable from other devices on the LAN
  // (phones/tablets/other PCs) at http://<this-machine-ip>:<port>.
  // strictPort: fail loudly if 3005 is taken instead of silently moving to 3006.
  // Supabase auth redirects are allow-listed per exact origin, so a drifting port
  // breaks password reset / email confirmation with no obvious cause.
  server: { host: true, port: 3005, strictPort: true },
  preview: { host: true, port: 4173, strictPort: false },
  build: {
    // pdfmake + its embedded fonts are unavoidably large but are lazy-loaded
    // (dynamic import on export), so don't warn about that known chunk.
    chunkSizeWarningLimit: 1500,
    rollupOptions: {
      output: {
        // Split heavy/optional vendors into their own chunks so they load only
        // when needed (pdf/excel export) and keep the initial bundle small.
        manualChunks: {
          "vendor-pdf": ["pdfmake"],
          "vendor-xlsx": ["xlsx"],
          "vendor-charts": ["recharts"],
          "vendor-react": ["react", "react-dom", "react-router-dom"],
        },
      },
    },
  },
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
  },
});
